spring:
  application:
    name: api-gateway

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/inventory/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
